In [8]:
import pandas as pd
from pathlib import Path

if "candidate_paths" not in globals():
    if "base_dir" not in globals():
        base_dir = Path.cwd()

    if "candidate_paths" not in globals():
        candidate_paths = [
            base_dir / "data" / "raw" / "students_messy.csv",
            base_dir.parent / "data" / "raw" / "students_messy.csv",
        ]

students_path = next(
    (p for p in candidate_paths if p.exists()),
    base_dir / "data" / "raw" / "students_messy.csv"
)

students = pd.read_csv(
    students_path,
    na_values=["", "missing", "N/A", "-"]
)
print(students.head())
print(students.shape)
print(students.dtypes)
print(students.isna().sum())
print("Exact duplicates:", students.duplicated().sum())

   student_id         name program        city  attendance  assignment  \
0        1001     Ali Khan    BSAI   Islamabad        85.0        78.0
1        1002   Sara Ahmed   BS AI   islamabad         NaN        88.0
2        1003  Ukash Irfan    BSAI  Rawalpindi        92.0        80.0
3        1004  Ayesha Noor    BSAI         Rwp       110.0        86.0
4        1005    Hamza Ali   BSCS    Islamabad        74.0        70.0

   midterm  final admission_date
0     72.0   81.0     2025-09-01
1     68.0   75.0     01/09/2025
2      NaN   88.0    2025/09/011
3     75.0   90.0     09-01-2025
4     52.0    NaN     2025-09-01
(10, 9)
student_id          int64
name                  str
program               str
city                  str
attendance        float64
assignment        float64
midterm           float64
final             float64
admission_date        str
dtype: object
student_id        0
name              0
program           0
city              1
attendance        1
assignment        1
midterm           1
final             1
admission_date    0
dtype: int64
Exact duplicates: 0

In [9]:
column1 = ["student_id", "name", "attendance", "assignment", "midterm", "final"]
print("\nSix-column Performance View:")
if "students" not in globals():

    base_dir = Path.cwd()
    candidate_paths = [
        base_dir / "data" / "raw" / "students_messy.csv",
        base_dir.parent / "data" / "raw" / "students_messy.csv",
    ]
    students_path = next(
        (p for p in candidate_paths if p.exists()),
        base_dir / "data" / "raw" / "students_messy.csv"
    )
    students = pd.read_csv(
        students_path,
        na_values=["", "missing", "N/A", "-", "NaN"]
    )

print(students[column1])

Six-column Performance View:
   student_id           name  attendance  assignment  midterm  final
0        1001       Ali Khan        85.0        78.0     72.0   81.0
1        1002     Sara Ahmed         NaN        88.0     68.0   75.0
2        1003    Ukash Irfan        92.0        80.0      NaN   88.0
3        1004    Ayesha Noor       110.0        86.0     75.0   90.0
4        1005      Hamza Ali        74.0        70.0     52.0    NaN
5        1006   Zainab Malik        81.0        91.0     84.0   93.0
6        1007    Ajmal Ukash        69.0        60.0     48.0   55.0
7        1008   Maryam Iqbal        88.0        89.0     87.0   94.0
8        1009  Basheer Mehdi        -5.0        55.0     42.0   49.0
9        1010      Hira Khan        79.0         NaN     72.0   80.0

In [10]:
students_bsai = students[students["program"].str.contains("AI", case=False, na=False)]
print("\nStudents Likely have AI programs:")
print(students_bsai[["student_id", "name", "program"]])

Students Likely have AI programs:
   student_id          name program
0        1001      Ali Khan    BSAI
1        1002    Sara Ahmed   BS AI
2        1003   Ukash Irfan    BSAI
3        1004   Ayesha Noor    BSAI
6        1007   Ajmal Ukash      AI
7        1008  Maryam Iqbal    BSAI

In [11]:
low_attendance = students.loc[students["attendance"] < 75]
low_attendance[["student_id", "name", "attendance"]]

   student_id           name  attendance
4        1005      Hamza Ali        74.0
6        1007    Ajmal Ukash        69.0
8        1009  Basheer Mehdi        -5.0

In [12]:
high_final = students.loc[students["final"] >= 80]
print("\nHigh Final Scores:")
print(high_final[["student_id", "name", "final"]])

High Final Scores:
   student_id          name  final
0        1001      Ali Khan   81.0
2        1003   Ukash Irfan   88.0
3        1004   Ayesha Noor   90.0
5        1006  Zainab Malik   93.0
7        1008  Maryam Iqbal   94.0
9        1010     Hira Khan   80.0

In [13]:
performance = students[["student_id", "name", "attendance", "assignment", "midterm", "final"]].copy()
performance_sorted = performance.sort_values(
    by="final", ascending=False, na_position="last"
)
print("\nPerformance Ranking:")
print(performance_sorted)

Performance Ranking:
   student_id           name  attendance  assignment  midterm  final
7        1008   Maryam Iqbal        88.0        89.0     87.0   94.0
5        1006   Zainab Malik        81.0        91.0     84.0   93.0
3        1004    Ayesha Noor       110.0        86.0     75.0   90.0
2        1003    Ukash Irfan        92.0        80.0      NaN   88.0
0        1001       Ali Khan        85.0        78.0     72.0   81.0
9        1010      Hira Khan        79.0         NaN     72.0   80.0
1        1002     Sara Ahmed         NaN        88.0     68.0   75.0
6        1007    Ajmal Ukash        69.0        60.0     48.0   55.0
8        1009  Basheer Mehdi        -5.0        55.0     42.0   49.0
4        1005      Hamza Ali        74.0        70.0     52.0    NaN

In [15]:
cleaning_log = []
students = students.drop_duplicates().reset_index(drop=True)
cleaning_log.append({"student_id": "1003", "column": "whole row",
                     "original_value": "exact duplicate", "decision": "Keep first occurrence",
                     "reason": "All column values match; one redundant row removed"})

In [16]:
students["program"] = students["program"].astype("string").str.strip()
students["city"] = students["city"].astype("string").str.strip()
students[["program", "city"]]

  program        city
0    BSAI   Islamabad
1   BS AI   islamabad
2    BSAI  Rawalpindi
3    BSAI         Rwp
4    BSCS   Islamabad
5    BSDS  RAWALPINDI
6      AI   Islamabad
7    BSAI        <NA>
8    BSCS   Islamabad
9   BS DS  Rawalpindi

In [17]:
students["city"] = students["city"].str.title()
students["city"] = students["city"].replace({"Rwp": "Rawalpindi"})
students["city"] = students["city"].fillna("Unknown")
print("cities:", students["city"].unique())

cities: <StringArray>
['Islamabad', 'Rawalpindi', 'Unknown']
Length: 3, dtype: string

In [18]:
students["student_id"] = students["student_id"].astype("string")
conversion_columns = ["attendance", "assignment", "midterm", "final"]
missing_before_conversion = students[conversion_columns].isna().sum()

In [19]:
for column in conversion_columns:
    students[column] = pd.to_numeric(students[column], errors="coerce")
new_missing = students[conversion_columns].isna().sum() - missing_before_conversion
print(students.dtypes)
print("New missing values:")
print(new_missing)

student_id         string
name                  str
program            string
city               string
attendance        float64
assignment        float64
midterm           float64
final             float64
admission_date        str
dtype: object
New missing values:
attendance    0
assignment    0
midterm       0
final         0
dtype: int64

In [20]:
missing_before_imputation = students[conversion_columns].isna().sum().copy()
affected_ids= {}
for column in conversion_columns:
    affected_ids[column] = students.loc[students[column].isna(), "student_id"].tolist()
students[f"{column}_imputed"] = students[column].isna()
print("Affected IDs:", affected_ids)

Affected IDs: {'attendance': ['1002'], 'assignment': ['1010'], 'midterm': ['1003'], 'final': ['1005']}

In [21]:
for column in ["assignment", "midterm", "final"]:
    median_value = students[column].median()
    students[f"{column}_imputed"] = students[column].isna()

    for student_id in affected_ids.get(column, []):
        cleaning_log.append({
            "student_id": student_id,
            "column": column,
            "original_value": "missing",
            "decision": f"Fill with column median {median_value}",
            "reason": "Classroom simulation only; retained imputation flag"
        })

    students[column] = students[column].fillna(median_value)

students[["student_id", "assignment", "midterm", "final",
          "assignment_imputed", "midterm_imputed", "final_imputed"]]

,student_id,assignment,midterm,final,assignment_imputed,midterm_imputed,final_imputed
0,1001,78.0,72.0,81.0,False,False,False
1,1002,88.0,68.0,75.0,False,False,False
2,1003,80.0,72.0,88.0,False,True,False
3,1004,86.0,75.0,90.0,False,False,False
4,1005,70.0,52.0,81.0,False,False,True
5,1006,91.0,84.0,93.0,False,False,False
6,1007,60.0,48.0,55.0,False,False,False
7,1008,89.0,87.0,94.0,False,False,False
8,1009,55.0,42.0,49.0,False,False,False
9,1010,80.0,72.0,80.0,True,False,False

In [22]:
invalid_mask = (students[conversion_columns] < 0) | (students[conversion_columns] > 100)
invalid_records = students.loc[invalid_mask.any(axis=1)].copy()
invalid_mask = (students[conversion_columns] < 0) | (students[conversion_columns] > 100)
invalid_records = students.loc[invalid_mask.any(axis=1)].copy()
invalid_records

,student_id,name,program,city,attendance,assignment,midterm,final,admission_date,final_imputed,assignment_imputed,midterm_imputed
3,1004,Ayesha Noor,BSAI,Rawalpindi,110.0,86.0,75.0,90.0,09-01-2025,False,False,False
8,1009,Basheer Mehdi,BSCS,Islamabad,-5.0,55.0,42.0,49.0,2025-09-04,False,False,False